default: &default
  ECWIDSHOP_MAILER_DEFAULT_FROM: "Ecwid eShop <store@example.com>"
  ECWIDSHOP_MAILER_NOTIFICATION_EMAIL: store@example.com
  # ECWIDSHOP_PAYMENT_CONFIRMATION_EMAIL_BODY_EN: ""
  # ECWIDSHOP_PAYMENT_CONFIRMATION_EMAIL_SUBJECT_EN: ""
  # ECWIDSHOP_PAYMENT_CONFIRMATION_EMAIL_BODY_ET: |
  #   Tere!
  #
  #   Täname, et sooritasite tellimuse %{shop_name} e-poest.
  #
  #   --- Tellimus %{shop_name} e-poest ---
  #
  #   Tellitud toode: %{payment_description}
  #   Maksumus: %{amount}
  #
  #   Lugupidamisega
  #   %{shop_name}
  # ECWIDSHOP_PAYMENT_CONFIRMATION_EMAIL_SUBJECT_ET: "Teie %{shop_name} e-poe makse kinnitus"
  # ECWIDSHOP_SHOP_NAME: myhost.com

development:
  <<: *default
  ECWIDSHOP_AUTHENTICATION_PASSWORD: secret
  ECWIDSHOP_AUTHENTICATION_USERNAME: shop@example.com
  ECWIDSHOP_BANK_KREDIIDIPANK_ENABLED: "true"
  ECWIDSHOP_BANK_LHV_ENABLED: "true"
  ECWIDSHOP_BANK_NORDEA_ENABLED: "true"
  ECWIDSHOP_BANK_SAMPO_ENABLED: "true"
  ECWIDSHOP_BANK_SEB_ENABLED: "true"
  ECWIDSHOP_BANK_SWEDBANK_ENABLED: "true"
  ECWIDSHOP_CERTS_FOLDER: spec/certificates
  # ECWIDSHOP_ECWID_SHOP_ID: ""
  # ECWIDSHOP_ECWID_ORDER_API_KEY: ""
  ECWIDSHOP_ESTCARD_ENABLED: "true"
  ECWIDSHOP_MAILER_DELIVERY_METHOD: smtp
  ECWIDSHOP_PROVIDER_RETURN_HOST: http://localhost:3000
  ECWIDSHOP_SHOP_EXTERNAL_URL: http://example.com/shop
  ECWIDSHOP_SHOP_EXTERNAL_RETURN_URL: http://example.com/shop
  ECWIDSHOP_SMTP_DOMAIN: example.com
  ECWIDSHOP_SMTP_SERVER: localhost
  ECWIDSHOP_SMTP_SERVER_PORT: "1025"

production:
  <<: *default
  # ECWIDSHOP_AUTHENTICATION_PASSWORD: ""
  # ECWIDSHOP_AUTHENTICATION_USERNAME: ""
  ECWIDSHOP_BANK_KREDIIDIPANK_ENABLED: "false"
  ECWIDSHOP_BANK_LHV_ENABLED: "false"
  ECWIDSHOP_BANK_NORDEA_ENABLED: "false"
  ECWIDSHOP_BANK_SAMPO_ENABLED: "false"
  ECWIDSHOP_BANK_SEB_ENABLED: "false"
  ECWIDSHOP_BANK_SWEDBANK_ENABLED: "false"
  ECWIDSHOP_CERTS_FOLDER: config/certificates
  # ECWIDSHOP_CERTS_FULL_ROOT: ""
  # ECWIDSHOP_ECWID_SHOP_ID: ""
  # ECWIDSHOP_ECWID_ORDER_API_KEY: ""
  ECWIDSHOP_ESTCARD_ENABLED: "false"
  ECWIDSHOP_MAILER_DELIVERY_METHOD: smtp
  # ECWIDSHOP_PROVIDER_RETURN_HOST: ""
  # ECWIDSHOP_SECRET_KEY_BASE: ""
  # ECWIDSHOP_SHOP_EXTERNAL_URL: ""
  # ECWIDSHOP_SHOP_EXTERNAL_RETURN_URL: ""
  # ECWIDSHOP_SMTP_AUTHENTICATION: ""
  # ECWIDSHOP_SMTP_DOMAIN: example.com
  # ECWIDSHOP_SMTP_ENABLE_STARTTLS_AUTO: "true"
  # ECWIDSHOP_SMTP_PASSWORD: ""
  # ECWIDSHOP_SMTP_SERVER: localhost
  # ECWIDSHOP_SMTP_SERVER_PORT: "25"
  # ECWIDSHOP_SMTP_USER_NAME: ""

test:
  <<: *default
  ECWIDSHOP_AUTHENTICATION_PASSWORD: secret
  ECWIDSHOP_AUTHENTICATION_USERNAME: shop@example.com
  ECWIDSHOP_BANK_KREDIIDIPANK_ENABLED: "true"
  ECWIDSHOP_BANK_LHV_ENABLED: "true"
  ECWIDSHOP_BANK_NORDEA_ENABLED: "true"
  ECWIDSHOP_BANK_SAMPO_ENABLED: "true"
  ECWIDSHOP_BANK_SEB_ENABLED: "true"
  ECWIDSHOP_BANK_SWEDBANK_ENABLED: "true"
  ECWIDSHOP_CERTS_FOLDER: spec/certificates
  ECWIDSHOP_ESTCARD_ENABLED: "true"
  ECWIDSHOP_MAILER_DELIVERY_METHOD: test
  ECWIDSHOP_PROVIDER_RETURN_HOST: http://localhost.test
  ECWIDSHOP_SHOP_EXTERNAL_URL: http://example.com/shop
  ECWIDSHOP_SHOP_EXTERNAL_RETURN_URL: http://example.com/shop
