development:
  mailer:
    delivery_method: test
    from: "My Store Development <store-development@mycompany.com>"
    to: office-development@mycompany.com

production:
  mailer:
    delivery_method: smtp
    from: "My Store <store@mycompany.com>"
    to: office@mycompany.com

test:
  mailer:
    delivery_method: test
    from: "My Store Test <store-test@mycompany.com>"
    to: office-test@mycompany.com
