swedbank:
  service_url: https://www.seb.ee/cgi-bin/dv.sh/un3min.r
  return_url: http://ecwid-pizzeria.local/ipizza/callback/seb/return
  cancel_url: http://ecwid-pizzeria.local/ipizza/callback/seb/cancel
  login: testvpos
  file_cert: ./certificates/seb_test_pub.crt
  file_key: ./certificates/seb_test_priv.pem
  key_secret: foobar
  encoding: UTF-8
  snd_id: testvpos

seb:
  service_url: https://www.seb.ee/cgi-bin/dv.sh/un3min.r
  return_url: http://ecwid-pizzeria.local/ipizza/callback/seb/return
  cancel_url: http://ecwid-pizzeria.local/ipizza/callback/seb/cancel
  login: testvpos
  file_cert: ./certificates/seb_test_pub.crt
  file_key: ./certificates/seb_test_priv.pem
  key_secret: foobar
  encoding: UTF-8
  snd_id: testvpos